# Generated by Django 4.2.14 on 2024-07-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_store', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='unique_department_category__name'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='unique_location_department_name'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_category_subcategory__name'),
        ),
    ]
